### ISSUE TITLE
the examples:connect returns an error.

### ISSUE THREAD

**Issue by b-yap** [stellarbeat/js-stellar-node-connector#25]
I am executing `yarn examples:connect 139.59.221.81 11625` as suggested in the readme,  and it returns an error. Even with a different ip.
```
rcv StellarMessage of type errorMsg: AAAAAAAAAAIAAAAWd3JvbmcgcHJvdG9jb2wgdmVyc2lvbgAA
```
I've decoded it, and it says _wrong protocol version_ ?

**Comment by pieterjan84** [comment]
You can specify the protocol versions for the example in a .env file (see .env.dist and [configuration](https://github.com/stellarbeat/js-stellar-node-connector#configuration)). LEDGER_VERSION and OVERLAY_VERSION are the most important ones. 
If you want to connect to a node on the stellar public/test network, you can find the versions on https://stellarbeat.io, on the node's dashboard page.

**Comment by b-yap** [comment]
thanks @pieterjan84!
