### ISSUE TITLE
Verified Nodes

### ISSUE THREAD

**Issue by jeffditullio** [stellarbeat/js-stellar-node-connector#3]
Eno is listed here: https://github.com/stellar/dashboard/blob/master/common/nodes.js but is not marked verified in the json output.

Also, consider using this as well: https://github.com/stellar/docs/blob/master/validators.md

**Comment by pieterjan84** [comment]
Verified status is no longer supported by stellar.org so I'm going to remove it.

Validators.md does not contain structured data so I don't parse it. However when I notice an update I will add it manually for now.
