### ISSUE TITLE
Validator Participation Level

### ISSUE THREAD

**Issue by jeffditullio** [stellarbeat/js-stellar-node-connector#4]
Is it possible to figure out the validator participation level? https://www.stellar.org/developers/stellar-core/software/admin.html#level-of-participation-to-the-network

**Comment by pieterjan84** [comment]
I don't think so. But I think nodes without quorumSets are watchers, others are validators. Or it could be that the crawler just hasn't picked up their quorum sets. If you have a lead on how to detect this, let me know. Closing issue because I don't think a solution is possible.
